WITH BASE_INFO AS
 (SELECT Y.YEAR_TIMEKEY,
         Y.MONTH_TIMEKEY,
         Y.WEEK_IN_YEAR,
         Y.DATE_TIMEKEY AS DAY_TIMEKEY,
         X.PRODUCT_DESC,
         X.MODELTYPE,
         X.LOT_ID,
         X.DFTCODE_QTY,
         X.GLS_TTL,
         X.PNL_QTY_PER_GLS
    FROM DWD_DFTCODE_D_LOT X
    LEFT JOIN EDS_CALENDAR Y
      ON (X.REPORTDATE = TO_DATE(Y.DATE_TIMEKEY, 'YYYYMMDD') AND
         Y.SHIFT_NAME = 'A' AND Y.FACTORY = 'LBP')
   WHERE (X.DFTCODE IS NULL OR SUBSTR(X.DFTCODE, 1, 1) != 'E')
     AND X.LOT_ID LIKE '6%'
     AND SUBSTR(X.LOT_ID, 7, 1) != 'D'
     AND X.FLOORNAME = '4' --传参
     AND X.PRODUCT_SIZE >= 4.0
     AND X.PRODUCT_SIZE <= 10.0
     AND X.PRODUCT_DESC NOT LIKE '%Flow'
     AND Y.YEAR_TIMEKEY = '2020'
     AND X.REPORTDATE <= TO_DATE('20201107', 'YYYYMMDD') --传参 ENDTIME 
  ),
FENMU_INFO AS
 (SELECT YEAR_TIMEKEY,
         MONTH_TIMEKEY,
         WEEK_IN_YEAR,
         DAY_TIMEKEY,
         PRODUCT_DESC,
         MODELTYPE,
         SUM(GLS_TTL * PNL_QTY_PER_GLS) TOTALP,
         COUNT(LOT_ID) LOT_COUNT
    FROM (SELECT T.YEAR_TIMEKEY,
                 T.MONTH_TIMEKEY,
                 T.WEEK_IN_YEAR,
                 T.DAY_TIMEKEY,
                 T.PRODUCT_DESC,
                 T.MODELTYPE,
                 T.LOT_ID,
                 T.GLS_TTL,
                 T.PNL_QTY_PER_GLS
            FROM BASE_INFO T
           GROUP BY T.YEAR_TIMEKEY,
                    T.MONTH_TIMEKEY,
                    T.WEEK_IN_YEAR,
                    T.DAY_TIMEKEY,
                    T.PRODUCT_DESC,
                    T.MODELTYPE,
                    T.LOT_ID,
                    T.GLS_TTL,
                    T.PNL_QTY_PER_GLS)
   GROUP BY YEAR_TIMEKEY,
            MONTH_TIMEKEY,
            WEEK_IN_YEAR,
            DAY_TIMEKEY,
            PRODUCT_DESC,
            MODELTYPE
  
  ),
FENZI_INFO AS
 (SELECT T.YEAR_TIMEKEY,
         T.MONTH_TIMEKEY,
         T.WEEK_IN_YEAR,
         T.DAY_TIMEKEY,
         T.PRODUCT_DESC,
         T.MODELTYPE,
         SUM(T.DFTCODE_QTY) AS DFTCODE_TTL
    FROM BASE_INFO T
   GROUP BY T.YEAR_TIMEKEY,
            T.MONTH_TIMEKEY,
            T.WEEK_IN_YEAR,
            T.DAY_TIMEKEY,
            T.PRODUCT_DESC,
            T.MODELTYPE)

-- 年良率
SELECT T.YEAR_TIMEKEY AS DAYSTR,
       T.PRODUCT_DESC || '(' || T.MODELTYPE || ')' AS PRODUCT_DESC,
       (1 - ROUND(SUM(T1.DFTCODE_TTL) / SUM(T.TOTALP), 4)) * 100 || '%' || '(' ||
       SUM(T.LOT_COUNT) || ')' AS RATE,
       1 AS SEQ
  FROM FENMU_INFO T
  LEFT JOIN FENZI_INFO T1
    ON (T.YEAR_TIMEKEY = T1.YEAR_TIMEKEY AND
       T.MONTH_TIMEKEY = T1.MONTH_TIMEKEY AND
       T.WEEK_IN_YEAR = T1.WEEK_IN_YEAR AND T.DAY_TIMEKEY = T1.DAY_TIMEKEY AND
       T.PRODUCT_DESC = T1.PRODUCT_DESC AND T.MODELTYPE = T1.MODELTYPE)
 GROUP BY T.YEAR_TIMEKEY, T.PRODUCT_DESC, T.MODELTYPE
UNION
-- 月良率
SELECT SUBSTR(T.MONTH_TIMEKEY, 5, 2),
       T.PRODUCT_DESC || '(' || T.MODELTYPE || ')' AS PRODUCT_DESC,
       (1 - ROUND(SUM(T1.DFTCODE_TTL) / SUM(T.TOTALP), 4)) * 100 || '%' || '(' ||
       SUM(T.LOT_COUNT) || ')' AS RATE,
       2 AS SEQ
  FROM FENMU_INFO T
  LEFT JOIN FENZI_INFO T1
    ON (T.YEAR_TIMEKEY = T1.YEAR_TIMEKEY AND
 T.MONTH_TIMEKEY = T1.MONTH_TIMEKEY AND
 T.WEEK_IN_YEAR = T1.WEEK_IN_YEAR AND T.DAY_TIMEKEY = T1.DAY_TIMEKEY AND
 T.PRODUCT_DESC = T1.PRODUCT_DESC AND T.MODELTYPE = T1.MODELTYPE)
 GROUP BY SUBSTR(T.MONTH_TIMEKEY, 5, 2), T.PRODUCT_DESC, T.MODELTYPE
UNION
-- 周良率
SELECT 'W' || T.WEEK_IN_YEAR AS WEEK_IN_YEAR,
       T.PRODUCT_DESC || '(' || T.MODELTYPE || ')' AS PRODUCT_DESC,
       (1 - ROUND(SUM(T1.DFTCODE_TTL) / SUM(T.TOTALP), 4)) * 100 || '%' || '(' ||
       SUM(T.LOT_COUNT) || ')' AS RATE,
       3 AS SEQ
  FROM FENMU_INFO T
  LEFT JOIN FENZI_INFO T1
    ON (T.YEAR_TIMEKEY = T1.YEAR_TIMEKEY AND
 T.MONTH_TIMEKEY = T1.MONTH_TIMEKEY AND
 T.WEEK_IN_YEAR = T1.WEEK_IN_YEAR AND T.DAY_TIMEKEY = T1.DAY_TIMEKEY AND
 T.PRODUCT_DESC = T1.PRODUCT_DESC AND T.MODELTYPE = T1.MODELTYPE)
 WHERE T.WEEK_IN_YEAR > TO_CHAR(TO_DATE('20201108', 'YYYYMMDD'), 'iw') - 4 -- 传入endtime
 AND T.WEEK_IN_YEAR <= TO_CHAR(TO_DATE('20201108', 'YYYYMMDD'), 'iw') -- 传入endtime
 GROUP BY 'W' || T.WEEK_IN_YEAR, T.PRODUCT_DESC, T.MODELTYPE
UNION
-- 天良率
SELECT T.DAY_TIMEKEY,
       T.PRODUCT_DESC || '(' || T.MODELTYPE || ')' AS PRODUCT_DESC,
       (1 - ROUND(SUM(T1.DFTCODE_TTL) / SUM(T.TOTALP), 4)) * 100 || '%' || '(' ||
       SUM(T.LOT_COUNT) || ')' AS RATE,
       4 AS SEQ
  FROM FENMU_INFO T
  LEFT JOIN FENZI_INFO T1
    ON (T.YEAR_TIMEKEY = T1.YEAR_TIMEKEY AND
 T.MONTH_TIMEKEY = T1.MONTH_TIMEKEY AND
 T.WEEK_IN_YEAR = T1.WEEK_IN_YEAR AND T.DAY_TIMEKEY = T1.DAY_TIMEKEY AND
 T.PRODUCT_DESC = T1.PRODUCT_DESC AND T.MODELTYPE = T1.MODELTYPE)
 WHERE T.DAY_TIMEKEY >= '20201102' -- 传入starttime
 AND T.DAY_TIMEKEY <= '20201111' -- 传入endtime
 GROUP BY T.DAY_TIMEKEY, T.PRODUCT_DESC, T.MODELTYPE
 ORDER BY SEQ
